---
title: "Analysis"
output: html_document
---

```{r setup, include=FALSE}
library(foreign)
library(jsonlite)
library(dplyr)
library(ggplot2)
library(cowplot)
```

## Read in data

```{r}
data <- inner_join(
  read.dbf('../data/holc-shapefile/holc_ad_data.dbf'),
  rbind(fromJSON('../data/task-exports/temperatures-2020.json'), fromJSON('../data/task-exports/temperatures-2000.json')),
  by = c('neighborho' = 'id')
) %>% 
  rename(holc_grade = holc_grade.x) %>% 
  filter(holc_grade != 'E') %>% 
  select(state, city, holc_grade, temperature, year)
data
```

## Visualize data

```{r}
data %>% ggplot(aes(temperature)) +
  geom_density() +
  facet_wrap(~ holc_grade)
```

## Tukey-Kramer test

```{r}
TukeyHSD(aov(temperature ~ holc_grade, data = data %>% filter(year == 2020)))
```

```{r}
southernCities <- strsplit("Birmingham,Mobile,Montgomery,Little Rock,Jacksonville,Miami,St. Petersburg,Tampa,Atlanta,Augusta,Columbus,Macon,Savannah,Evansville,Wichita,Lexington,Louisville,New Orleans,Shreveport,Springfield,Jackson,Asheville,Charlotte,Durham,Greensboro,Winston-Salem,Oklahoma City,Tulsa,Columbia,Chattanooga,Knoxville,Memphis,Nashville,Austin,Beaumont,Dallas,Fort Worth,Galveston,Houston,Port Arthur,San Antonio,Waco,Lynchburg,Newport News,Norfolk,Richmond,Roanoke,Charleston", ",")[[1]]

filteredData <- data %>% filter(city %in% southernCities)

plot(TukeyHSD(aov(temperature ~ holc_grade, data = filteredData)), las = 1, tcl = -.4)
```


```{r}
plot(TukeyHSD(aov(temperature ~ holc_grade, data = filteredData)), las = 1, tcl = -.4)
tky = as.data.frame(TukeyHSD(aov(temperature ~ holc_grade, data = filteredData))$holc_grade)
tky$pair = rownames(tky)

# Plot pairwise TukeyHSD comparisons and color by significance level
tkyPlot <- ggplot(tky, aes(colour=cut(`p adj`, c(0, 0.01, 0.05, 1), 
                           label=c("p < 0.01","p < 0.05","Non-Sig")))) +
  geom_hline(yintercept=0, lty="11", colour="grey30") +
  geom_errorbar(aes(pair, ymin=lwr, ymax=upr), width=0.2) +
  geom_point(aes(pair, diff)) +
  labs(colour="") +
  coord_flip() +
  theme_minimal_vgrid(12) +
  labs(y = 'Difference in temperature', x = 'Pair')
tkyPlot

ggsave(
  'test.png',
  plot,
  device = 'png',
  width = 6.7,
  height = 5.5,
  units = 'in',
  dpi = 300
  )
plot <- data %>%
  filter(city == "Chicago") %>%
  ggplot(aes(temperature, fill = holc_grade)) +
  geom_density(alpha = 0.6) +
  facet_grid(holc_grade ~ year, switch = "y", scales="free_y") +
  scale_y_continuous(expand = expansion(mult = c(0, 0.05))) +
  guides(fill = FALSE) +
  scale_fill_manual(values = c(
    "#76a865", "#7cb5bd", "#ffff00", "#d9838d"
  )) +
  theme_minimal_vgrid(12) +
  theme(axis.line.y = element_blank(), axis.text.y = element_blank(), axis.ticks.y = element_blank(), axis.title.y = element_blank(), strip.text.y.left = element_text(angle = 0)) +
  labs(y = 'Mean summertime temperature')
plot

ggsave(
  'test.png',
  plot,
  device = 'png',
  width = 6.7,
  height = 5.5,
  units = 'in',
  dpi = 300
  )
```


